/* HISTORY RESULTS*/
export const HISTORY_GET_RESULTS = "HISTORY_GET_RESULTS";
export const HISTORY_GET_RESULTS_SUCCESS = "HISTORY_GET_RESULTS_SUCCESS";
export const HISTORY_GET_RESULTS_ERROR = "HISTORY_GET_RESULTS_ERROR";
export const CREATE_HISTORY_RECORD = "CREATE_HISTORY_RECORD";
export const CREATE_HISTORY_RECORD_SUCCESS = "CREATE_HISTORY_RECORD_SUCCESS";
export const CREATE_HISTORY_RECORD_ERROR = "CREATE_HISTORY_RECORD_ERROR";